export const COLOR_ONE = "#E41F7B";
export const COLOR_TWO = "#E0669D";
export const COLOR_THREE = "#EEEEEE";
export const BRANDS = [
  "maybelline",
  "dior",
  "anna sui",
  "annabelle",
  "benefit",
  "boosh",
  "burt's bees",
  "butter london",
  "c'est moi",
  "cargo cosmetics",
  "china glaze",
  "clinique",
  "coastal classic creation",
  "colourpop",
  "covergirl",
  "dalish",
  "deciem",
  "alva",
  "dr. hauschka",
  "e.l.f.",
  "essie",
  "fenty",
  "glossier",
  "green people",
  "iman",
  "l'oreal",
  "lotus cosmetics usa",
  "maia's mineral galaxy",
  "marcelle",
  "marienatie",
  "almay",
  "milani",
  "mineral fusion",
  "misa",
  "mistura",
  "moov",
  "nudus",
  "nyx",
  "orly",
  "pacifica",
  "penny lane organics",
  "physicians formula",
  "piggy paint",
  "pure anada",
  "rejuva minerals",
  "revlon",
  "sally b's skin yummies",
  "salon perfect",
  "sante",
  "sinful colours",
  "smashbox",
  "stila",
  "suncoat",
  "w3llpeople",
  "wet n wild",
  "zorah",
  "zorah biocosmetiques",
];

export const PRODUCT_TYPES = [
  "blush",
  "bronzer",
  "nail_polish",
  "mascara",
  "lipstick",
  "lip_liner",
  "foundation",
  "eyeshadow",
  "eyeliner",
  "eyebrow",
];

export const CATEGORIES = [
  "lipstick",
  "lip gloss",
  "liquid",
  "lip stain",
  "concealer",
  "contour",
  "Bb cc",
  "cream",
  "mineral",
  "powder",
  "highlighter",
  "pencil",
  "palette",
  "gel",
];
export const TAGS = [
  "Vegan",
  "Gluten free",
  "Canadian",
  "Natural",
  "Non-gmo",
  "Purpicks",
  "Organic",
  "Usda organic",
  "Certclean",
  "Ewg verified",
  "Hypoallergenic",
  "No talc",
  "Ecocert",
  "Water free",
  "Cruelty free",
  "Alcohol free",
  "Oil free",
  "Silicone free",
  "Peanut free product",
  "Chemical free",
  "Fair trade",
  "Sugar free",
  "Dairy free",
];
export const PAGE_SIZE = 10;
export const ANNOUNCEMENTS = [
  { text: "FREE SHIPPING ON ORDERS OVER 99 $" },
  { text: "DOWNLOAD APP - FREE SHIPPING ON YOUR FIRST ORDER" },
  { text: "CLICK & COLLECT-  FREE DELIVERY" },
  {
    text: "DOWNLOAD APP - %10 OFF YOUR FIRST ORDER | CODE: PRETTY10",
  },
];

export const PAY_WAYS = [
  { text: "Paypal", imgSrc: "/src/assets/PayPal.svg" },
  { text: "Visa", imgSrc: "/src/assets/Visa.svg" },
  { text: "Mastercard", imgSrc: "/src/assets/Mastercard.svg" },
];

export const IMGS = [
  {
    src: "/lips.png",
  },
  {
    src: "/brushes.png",
  },
  {
    src: "/nail-polish.png",
  },
  {
    src: "/single-pot.png",
  },
];
